### ISSUE TITLE
Feature Request: Recently Played

### ISSUE THREAD

**Issue by FoxxMD** [Exerra/node-musickit-api#5]
Hello, thanks for making this library!

Could you possibly add the [recently played](https://developer.apple.com/documentation/applemusicapi/get_recently_played_resources) resources endpoint to the personalized methods? I need this for work on my library [multi-scrobbler](https://github.com/FoxxMD/multi-scrobbler). If you don't have time in the near-future I'll try to go at myself.

**Comment by Exerra** [comment]
Hello, thanks for the kind words

Progress on personalized routes is kind of slow right now, mostly due to me working on an iOS app

I can, however, work on the "recently played" method and then push everything I have right now to NPM (as currently no personalized methods are available in npm). ETA on that could be 1-2 days probably, as I would need to write documentation too

Also, I checked out the issue where this got mentioned, my library also handles JWT, so all you need to do is pass the key, team id and key id to the constructor :)

**Comment by Exerra** [comment]
> I understand with the personalized routes there is a prerequisite to do authorization/callback from apple for individual users (to get the music user token) 

Yes, there is a prerequisite. Sadly I have not yet figured out how to do authorisation for the user (docs mention swift, but swift is not that practical for js haha), so currently you need to get a token by any means necessary and pass it into the constructor

**Comment by Exerra** [comment]
Did it!!!

![Sample code of how to use personalized resources](https://cdn.exerra.xyz/files/png/node-musickit-api/howToUse_getRecentlyPlayed().png)

This is how it is like right now

Do you feel like there should be any improvements?
